### ISSUE TITLE
Label Position Only Diagonal

### ISSUE THREAD

**Issue by ArzhurG** [GiantMolecularCloud/easy_aplpy#2]
The position of the labels of the maps in a channel map created with grid can be changed with the setting _grid_label_pos_, which takes an array of two numbers. However, the __helpers.py_ in the plot directory uses the first of the two numbers for both the x and y position of the labels. This means that the labels can only be positioned along a diagonal line, and not anywhere on the maps. Assuming the the second number is mean to be the y position, the issue can be fixed by changing the 0 on line 594 of __helper.py_ to a 1, so that second element of _grid_label_pos_ is used for the y.

**Comment by GiantMolecularCloud** [comment]
Thank you for noticing this bug and offering the solution!
grid_label_position was indeed meant to freely move the label across the figure panel.
I'm glad other people are able to use and understand my code. Please point out further bug when you come across them.

closed by 58f5b5c85f27b8828addbef2eaf85d6e645fadd7
